services:

  django:
    container_name: django
    build: social_media
    ports:
      - "8000:8000"
    volumes:
      - django-v:/django-app
          
  social:
    container_name: static
    build: static
    ports:
      - "8899:8899"
      - "8080:8080"
    volumes:
      - static:/var/www/social/
    depends_on:
      - django


volumes:

  django-v:
    driver: local
    name: django-v
    driver_opts:
      type: none
      o: bind
      device: /home/afanti/Desktop/social/social_media/

  static:
    driver: local
    name: static
    driver_opts:
      type: none
      o: bind
      device: /home/afanti/Desktop/social/static/website




