FROM python
                   
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libavcodec-extra \
    && apt-get clean

# Install yt-dlp (latest version of youtube-dl)
RUN pip install --upgrade pip && \
pip install yt-dlp

# Install other necessary Python packages
RUN pip install requests



WORKDIR /django-app

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD python manage.py makemigrations && \
    python manage.py migrate && \
    python manage.py runserver 0.0.0.0:8000